# Generated by Django 4.2.1 on 2023-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='mailing_failure_reason',
        ),
        migrations.AddField(
            model_name='lead',
            name='mailing_failed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Если поле осталось пустым после рассылки — значит рассылка прошла успешно.', null=True, verbose_name='когда случилась ошибка'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mailing_failure_description',
            field=models.TextField(blank=True, help_text='Описание для пользователя.', verbose_name='описание ошибки рассылки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mailing_failure_reason_code',
            field=models.CharField(blank=True, db_index=True, help_text='Англоязычный код ошибки по результатам рассылки, например "endless_loop".', max_length=100, verbose_name='код ошибки рассылки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mailing_failure_debug_details',
            field=models.TextField(blank=True, help_text='Описание ошибки рассылки. Поле хранит отладочную информацию для программиста.', verbose_name='отладочная информация об ошибке рассылки'),
        ),
    ]
